# Generated by Django 4.0 on 2021-12-18 11:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50)),
                ('authority_type', models.CharField(choices=[('Muncipality', 'Muncipality'), ('Corparation', 'Corparation'), ('Panchayath', 'panachayath')], default='Government', max_length=50)),
                ('center_pincode', models.PositiveIntegerField()),
                ('center_place', models.CharField(max_length=60)),
                ('center_type', models.CharField(choices=[('Hospital', 'Hospital'), ('CFLTC', 'CFLTC'), ('CSLTC', 'CSLTC'), ('Domicile', 'Domicle')], max_length=50)),
                ('center_ideantification_proof', models.FileField(upload_to='center_proof')),
                ('center_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('center_photo', models.ImageField(upload_to='center_photo')),
                ('status_appruval', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adhar', models.PositiveIntegerField(unique=True)),
                ('pincode', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adhar', models.PositiveIntegerField(unique=True)),
                ('pincode', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
                ('loaction', models.CharField(max_length=100)),
                ('lab_pincode', models.IntegerField()),
                ('lab_type', models.CharField(blank=True, choices=[('hospital', 'hospital'), ('private', 'private')], max_length=30, null=True)),
                ('lab_certificate', models.FileField(upload_to='lab_certificate')),
                ('lab_avilability', models.CharField(choices=[('available', 'avilable'), ('not_available', 'not_available')], default=[('available', 'avilable'), ('not_available', 'not_available')], max_length=30)),
                ('working_time', models.CharField(blank=True, max_length=40, null=True)),
                ('lab_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('image', models.ImageField(default='lab.jpg', upload_to='lab_image')),
                ('status_appruval', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('authority_type', models.CharField(choices=[('Muncipality', 'Muncipality'), ('Corparation', 'Corparation'), ('Panchayath', 'panachayath')], max_length=30)),
                ('authority_name', models.CharField(max_length=50)),
                ('ward_no', models.PositiveIntegerField()),
                ('village', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(upload_to='home')),
                ('status_appruval', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doctor_photo', models.ImageField(upload_to='doctor_iamge')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('doctor_certificate', models.FileField(upload_to='doctor_certificate')),
                ('qualification', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('doctor_avilability', models.CharField(blank=True, choices=[('available', 'avilable'), ('not_available', 'not_available')], max_length=50, null=True)),
                ('online_avilable', models.BooleanField(default=False)),
                ('status_appruval', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='DMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adhar', models.PositiveIntegerField(unique=True)),
                ('pincode', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
