# Generated by Django 4.0 on 2021-12-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='lab_phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='image',
            new_name='photo_of_lab',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
