# Generated by Django 4.0 on 2021-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmo',
            name='status_appruval',
            field=models.BooleanField(default=False),
        ),
    ]
