# Generated by Django 4.0 on 2021-12-18 21:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adhar', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Oother', 'Other')], max_length=20, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('house_name', models.CharField(blank=True, max_length=40, null=True)),
                ('place', models.CharField(blank=True, max_length=70, null=True)),
                ('authority_type', models.CharField(blank=True, choices=[('Muncipality', 'Muncipality'), ('Corparation', 'Corparation'), ('Panchayath', 'panachayath')], max_length=30, null=True)),
                ('authority_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.PositiveIntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(default='Thrissur', max_length=50)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('category a', 'category_a'), ('category_b', 'category_b'), ('category_c', 'category_c')], max_length=40, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_status', models.CharField(blank=True, choices=[('death with in one month', 'death_with_in_onemonth'), ('discharged', 'discharged'), ('shifted to CFLTC', 'shifted_to_CFLTC'), ('shifted to CSLTC', 'shifted_to_CSLTC'), ('shifted_to_domociline', 'shifted_to_domociline'), ('shifted_to_home', 'shifted_to_home'), ('death', 'death')], max_length=30, null=True)),
                ('test_date', models.DateField()),
                ('test_name', models.CharField(choices=[('antigen', 'antigen'), ('RTPCR', 'rtpcr')], default='RTPCR', max_length=50)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
