# Generated by Django 4.0 on 2021-12-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_remove_patientstatus_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='test_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
