# Generated by Django 4.0 on 2021-12-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_patientstatus_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstatus',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
