# Generated by Django 4.0 on 2021-12-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='category',
            field=models.CharField(blank=True, choices=[('category a', 'category_a'), ('category_b', 'category_b'), ('category_c', 'category_c')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='patient_hos_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
