# Generated by Django 4.0 on 2021-12-19 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
        ('center', '0006_remove_patient_category_remove_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar', models.PositiveIntegerField()),
                ('vaccine_name', models.CharField(choices=[('covisheild', 'covisheild'), ('covaxine', 'covaxine'), ('sputinic', 'sputinic')], default='covaxine', max_length=50)),
                ('dose_no', models.CharField(choices=[('first_dose', 'first_dose'), ('second_dose', 'second_dose')], default='first_dose', max_length=40)),
                ('fisrst_dose_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('second_dose_date', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_covid_dis', models.CharField(max_length=200)),
                ('post_covid_dis', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.PositiveIntegerField(blank=True, null=True)),
                ('ward_no', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_no', models.PositiveIntegerField(blank=True, null=True)),
                ('room_no', models.PositiveIntegerField(blank=True, null=True)),
                ('icu_no', models.PositiveIntegerField(blank=True, null=True)),
                ('ventilator_no', models.PositiveIntegerField(blank=True, null=True)),
                ('bed_availability', models.CharField(blank=True, choices=[('free', 'free'), ('occupied', 'occupied')], max_length=30, null=True)),
                ('bed_with_oxygen', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=30)),
                ('bed_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Oother', 'Other')], max_length=30)),
                ('patient_status', models.CharField(blank=True, choices=[('death with in one month', 'death_with_in_onemonth'), ('discharged', 'discharged'), ('shifted to CFLTC', 'shifted_to_CFLTC'), ('shifted to CSLTC', 'shifted_to_CSLTC'), ('shifted_to_domociline', 'shifted_to_domociline'), ('shifted_to_home', 'shifted_to_home'), ('death', 'death'), ('positive', 'positive'), ('negative', 'negative')], max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.bed'),
        ),
    ]
