# Generated by Django 4.0 on 2021-12-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_vaccine_disease_bed_patientstatus_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='patient_status',
        ),
    ]
