# Generated by Django 4.0 on 2021-12-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_remove_bed_patient_remove_bed_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patient'),
        ),
    ]
