# Generated by Django 4.0 on 2021-12-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_bed_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstatus',
            name='bed',
        ),
        migrations.AddField(
            model_name='bed',
            name='patient_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patientstatus'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_availability',
            field=models.CharField(choices=[('free', 'free'), ('occupied', 'occupied')], default='free', max_length=30),
        ),
    ]
