# Generated by Django 4.0 on 2021-12-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_patientstatus_bed_bed_patient_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
    ]
