# Generated by Django 4.0 on 2021-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_remove_bed_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Oother', 'Other')], max_length=30, null=True),
        ),
    ]
