# Generated by Django 4.0 on 2021-12-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
        ('center', '0013_remove_bed_patient_status_bed_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstatus',
            name='patient_hos_id',
        ),
        migrations.AddField(
            model_name='bed',
            name='patient_hos_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center'),
        ),
    ]
