# Generated by Django 4.0 on 2021-12-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_remove_patientstatus_patient_hos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient_hos_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_hos_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
