# Generated by Django 4.0 on 2021-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_remove_bed_patient_hos_id_patient_patient_hos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstatus',
            name='test_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
