# Generated by Django 4.0 on 2021-12-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_alter_patientstatus_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstatus',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='patientstatus',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='patientstatus',
            name='test_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(blank=True, choices=[('death with in one month', 'death_with_in_onemonth'), ('discharged', 'discharged'), ('shifted to CFLTC', 'shifted_to_CFLTC'), ('shifted to CSLTC', 'shifted_to_CSLTC'), ('shifted_to_domociline', 'shifted_to_domociline'), ('shifted_to_home', 'shifted_to_home'), ('death', 'death'), ('positive', 'positive'), ('negative', 'negative')], default='Postitive', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='test_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='test_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='test_name',
            field=models.CharField(choices=[('antigen', 'antigen'), ('RTPCR', 'rtpcr')], default='RTPCR', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientstatus',
            name='patient_status',
            field=models.CharField(blank=True, choices=[('death with in one month', 'death_with_in_onemonth'), ('discharged', 'discharged'), ('shifted to CFLTC', 'shifted_to_CFLTC'), ('shifted to CSLTC', 'shifted_to_CSLTC'), ('shifted_to_domociline', 'shifted_to_domociline'), ('shifted_to_home', 'shifted_to_home'), ('death', 'death'), ('positive', 'positive'), ('negative', 'negative')], default='Postitive', max_length=30, null=True),
        ),
    ]
