# Generated by Django 4.0 on 2021-12-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0018_alter_patient_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='center',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='center',
        ),
    ]
