# Generated by Django 4.0 on 2021-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0020_alter_vaccine_fisrst_dose_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='fisrst_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='second_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
