# Generated by Django 4.0 on 2021-12-19 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0021_alter_vaccine_fisrst_dose_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='fisrst_dose_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='second_dose_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
