# Generated by Django 3.2.6 on 2021-12-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dmo_status_appruval'),
        ('center', '0024_patient_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.home'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.home'),
        ),
    ]
