# Generated by Django 4.0 on 2021-12-19 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('replay', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.utcnow)),
                ('replay_date', models.DateTimeField(blank=True, default=patient.models.utc_tomorrow, null=True)),
                ('replay_status', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubts', models.TextField()),
                ('replay', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('replay_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
