# Generated by Django 4.0 on 2021-12-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True),
        ),
    ]
