# Generated by Django 3.2.6 on 2021-12-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0022_alter_vaccine_fisrst_dose_date_and_more'),
        ('patient', '0002_alter_complaint_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.patientstatus'),
        ),
    ]
