# Generated by Django 3.2.6 on 2021-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_chat_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solve_status',
            field=models.CharField(choices=[('solved', 'solved'), ('un_solved', 'un_solved')], default='un_solved', max_length=20),
        ),
    ]
