# Generated by Django 3.2.6 on 2021-12-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dmo_status_appruval'),
        ('patient', '0005_complaint_solve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.home'),
        ),
    ]
