# Generated by Django 4.0 on 2021-12-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.PositiveIntegerField()),
                ('test_name', models.CharField(choices=[('antigen', 'antigen'), ('RTPCR', 'rtpcr')], default='antigen', max_length=50)),
                ('test_cost', models.PositiveIntegerField()),
                ('test_avilability', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.lab')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
