# Generated by Django 4.0 on 2021-12-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_avilability',
            field=models.CharField(blank=True, choices=[('available', 'avilable'), ('not_available', 'not_available')], max_length=50, null=True),
        ),
    ]
