# Generated by Django 4.0 on 2021-12-19 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_lab_working_time_lab_lab_district_and_more'),
        ('center', '0018_alter_patient_patient_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(default='covid-19')),
                ('appruval', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.center')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
